### ISSUE TITLE
[ FR ] Mobile Support

### ISSUE THREAD

**Issue by stef-rausch** [victorb/obsidian-wielder#1]
Would you consider making the plugin available for mobile?

I did install it via BRAT and can't wait to try it out.

Thank you!

**Comment by victorb** [comment]
I didn't try it before, I've changed `isDesktopOnly` to `false`, so I could try it out, but seems something goes wrong when loading the plugin on mobile. Investigating why.

**Comment by stef-rausch** [comment]
Thanks for looking into it, @victorb!

**Comment by victorb** [comment]
Alright, 077bc435ae2060072119e615c4764aee25dcf16e fixed the issue. Now working on iOS and Android too :) 

If you're using it via BRAT, make sure Wielder's version ends up being 1.0.3

![obsidian-wielder](https://user-images.githubusercontent.com/459764/173330800-4a363332-b595-4c35-954e-a96365179faf.png)

![photo_2022-06-13_12-06-15](https://user-images.githubusercontent.com/459764/173330815-0e6e2917-e366-46ba-9369-00582a4b71f9.jpg)

Thanks for the report :tada: If you find any other issues related to mobile usage, please open a new issue.

**Comment by stef-rausch** [comment]
Thank you so much!
